[server]
headless             = true
enableCORS           = false
enableXsrfProtection = false

[theme]
base                     = "light"
primaryColor             = "#1AB868"
backgroundColor          = "#F2F6FA"
secondaryBackgroundColor = "#FFFFFF"
textColor                = "#071D35"
font                     = "sans serif"
